version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: typescript
    labels:
      - dependencies
    groups:
      build-utils:
        patterns:
          - '@iconify/*'
          - '@intlify/*'
          - '@rollup/*'
          - '@tailwindcss/*'
          - '@vitejs/*'
          - '@unhead/*'
          - '@vue/*'
          - happy-dom
          - rollup
          - unplugin-*
          - tailwindcss
          - vite
          - vite-*
          - vitest
          - vue-tsc
          - workbox-*
        update-types: [minor]
      commitlint:
        patterns: ['@commitlint/*']
        update-types: [minor]
      eslint:
        patterns: [eslint, 'eslint-*', '@antfu/eslint-config']
        update-types: [minor]
      fontsource:
        patterns: ['@fontsource/*']
        update-types: [minor]
      markdown:
        patterns:
          - '@types/markdown-it'
          - '@types/markdown-it-*'
          - gray-matter
          - markdown-it
          - markdown-it-*
          - prismjs
        update-types: [minor]
