image: 'ruby:2.3'

before_script:
    - gem install jekyll

stages:
    - deploy

pages:
    stage: deploy
    script:
        - jekyll build
    artifacts:
        paths:
            - public
    only:
        - master

