// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Colopon: typeof import('./components/widgets/colopon.vue')['default']
    HeroSection: typeof import('./components/sections/hero-section.vue')['default']
    MainLogo: typeof import('./components/main-logo.vue')['default']
    PageContent: typeof import('./components/page-content.vue')['default']
    PartnersSection: typeof import('./components/sections/partners-section.vue')['default']
    ReasoneSection: typeof import('./components/sections/reasone-section.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/site-footer.vue')['default']
    SiteHeader: typeof import('./components/site-header.vue')['default']
    SiteSection: typeof import('./components/site-section.vue')['default']
    WeBelieves: typeof import('./components/sections/we-believes.vue')['default']
    Widget: typeof import('./components/widgets/widget.vue')['default']
    WorkflowsSection: typeof import('./components/sections/workflows-section.vue')['default']
  }
}

export {}
