// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/app-link.vue')['default']
    HeadingSection: typeof import('./components/heading-section.vue')['default']
    MainLogo: typeof import('./components/main-logo.vue')['default']
    NavbarMenu: typeof import('./components/navbar-menu.vue')['default']
    PageContent: typeof import('./components/page-content.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBase: typeof import('./components/sections/section-base.vue')['default']
    SectionBelieves: typeof import('./components/sections/section-believes.vue')['default']
    SectionHero: typeof import('./components/sections/section-hero.vue')['default']
    SectionPartners: typeof import('./components/sections/section-partners.vue')['default']
    SectionReason: typeof import('./components/sections/section-reason.vue')['default']
    SectionWorkflows: typeof import('./components/sections/section-workflows.vue')['default']
    SiteFooter: typeof import('./components/site-footer.vue')['default']
    SiteHeader: typeof import('./components/site-header.vue')['default']
    SiteSection: typeof import('./components/site-section.vue')['default']
    WidgetBase: typeof import('./components/widgets/widget-base.vue')['default']
    WidgetColopon: typeof import('./components/widgets/widget-colopon.vue')['default']
  }
}

export {}
