name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Set up node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*

      - name: Build pages
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_PROJECT_ID: ${{ vars.PROJECT_ID }}
          VITE_GTM_ID: ${{ vars.GTM_ID }}
        run: |
          pnpm build

      - name: Store
        uses: actions/upload-artifact@v7
        with:
          overwrite: true
          name: static-build
          path: dist
